// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import TypedTitlesController from "./typed_titles_controller"
application.register("typed-titles", TypedTitlesController)

import UpvoteController from "./upvote_controller"
application.register("upvote", UpvoteController)

import UserProgressController from "./user_progress_controller"
application.register("user-progress", UserProgressController)
