// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CreateNewController from "./create_new_controller"
application.register("create-new", CreateNewController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TurboController from "./turbo_controller"
application.register("turbo", TurboController)

import UpvoteController from "./upvote_controller"
application.register("upvote", UpvoteController)

import UserProgressController from "./user_progress_controller"
application.register("user-progress", UserProgressController)
